name: Velero Binary Release

on:
  workflow_dispatch:
    inputs:
      tags:
        description: 'Tags'
jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 1
    - name: Unshallow
      run: git fetch --prune --unshallow
    - name: Set up Go 1.18
      uses: actions/setup-go@v3
      with:
        go-version: 1.18
    - name: Run GoReleaser
      uses: goreleaser/goreleaser-action@v3.1.0
      with:
        distribution: goreleaser
        version: v1.18.2
        args: release --clean
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
