name: Publish to Dockerhub ( VELERO-ARM64 )

on:
  workflow_dispatch:
    inputs:
      tags:
        description: 'Release Tags'

jobs:
  publish_dockerhub:
    runs-on: ubuntu-latest
    steps:
    - name: Check out the repo
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASS }}

    - name: Build velero and push Docker image
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: beclab/velero:${{ github.event.inputs.tags }}
        file: Dockerfile1
        build-args: |
          BIN=velero
          VERSION=${{ github.event.inputs.tags }}
          PKG=.
          TARGETOS=linux
          TARGETARCH=arm64
          RESTIC_VERSION=0.15.0
